# -*- coding: utf-8 -*-
"""Assignment1_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dg9ZPw-Ze9iJfqd2AqpY7V3NTD9foLSj
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread('sample_image.png')
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#increase the brightness
brightened_img = cv2.add(img, 80)
cv2_imshow(brightened_img)
cv2.waitKey(0)

#increase the contrast of the image
contrast_img = cv2.convertScaleAbs(img, alpha=4.5, beta=1.5)
cv2_imshow(contrast_img)
cv2.waitKey(0)

#generating negative image
negative_image = 255 - img
cv2_imshow(negative_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

#generating grayscale image
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

#read an image and then plot it's histogram
img = cv2.imread('sample_image.png')
plt.hist(img.ravel(), 256, [0, 256])
plt.show()

#apply thresholding on the sample image
_, thresholded_img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
cv2_imshow(thresholded_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

